apiVersion: apps/v1
kind: Deployment
metadata:
  name: python.py
spec:
  selector:
    matchLabels:
      app: python.py
  replicas: 2
  template:
    metadata:
      labels:
        app: python.py
    spec:
      containers:
      - name: myapp
        image: https://hub.docker.com/sonitamuluh/python.py:1.1
        ports:
        - containerPort: 8080
